version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      DB_NAME: mydatabase
      DB_USER: mydbuser
      DB_PASSWORD: mydbpassword
      DB_HOST: db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: